import 'package:flutter/material.dart';

enum LevelStatus {
  completed,
  active,
  locked,
}

class CourseLevel {
  final int levelNumber;
  final String code; // e.g. "01 • FOUNDATIONS"
  final String title; // e.g. "Solving Linear Equations"
  final String description;
  final LevelStatus status;
  final String stepProgress; // e.g. "Step 3 of 5"
  final String duration; // e.g. "8 min"
  final bool hasBonus;
  final String? bonusTitle; // e.g. "DAILY SPEED RUN"
  final List<String> keyConcepts;
  final String quizTopic;

  const CourseLevel({
    required this.levelNumber,
    required this.code,
    required this.title,
    required this.description,
    required this.status,
    required this.stepProgress,
    required this.duration,
    this.hasBonus = false,
    this.bonusTitle,
    this.keyConcepts = const [],
    required this.quizTopic,
  });

  bool get isCompleted => status == LevelStatus.completed;
  bool get isActive => status == LevelStatus.active;
  bool get isLocked => status == LevelStatus.locked;

  CourseLevel copyWith({
    int? levelNumber,
    String? code,
    String? title,
    String? description,
    LevelStatus? status,
    String? stepProgress,
    String? duration,
    bool? hasBonus,
    String? bonusTitle,
    List<String>? keyConcepts,
    String? quizTopic,
  }) {
    return CourseLevel(
      levelNumber: levelNumber ?? this.levelNumber,
      code: code ?? this.code,
      title: title ?? this.title,
      description: description ?? this.description,
      status: status ?? this.status,
      stepProgress: stepProgress ?? this.stepProgress,
      duration: duration ?? this.duration,
      hasBonus: hasBonus ?? this.hasBonus,
      bonusTitle: bonusTitle ?? this.bonusTitle,
      keyConcepts: keyConcepts ?? this.keyConcepts,
      quizTopic: quizTopic ?? this.quizTopic,
    );
  }
}

class LearningCourse {
  final String id;
  final String subjectId;
  final String subjectName;
  final String title;
  final String subtitle;
  final String description;
  final int iconCodePoint;
  final int progressPercent;
  final List<CourseLevel> levels;
  final String cadenceInsight;

  const LearningCourse({
    required this.id,
    required this.subjectId,
    required this.subjectName,
    required this.title,
    required this.subtitle,
    required this.description,
    required this.iconCodePoint,
    required this.progressPercent,
    required this.levels,
    required this.cadenceInsight,
  });

  // ignore: non_const_argument_for_const_parameter
  IconData get icon => IconData(iconCodePoint, fontFamily: 'MaterialIcons');

  CourseLevel? get activeLevel {
    try {
      return levels.firstWhere((l) => l.isActive);
    } catch (_) {
      return levels.isNotEmpty ? levels.first : null;
    }
  }

  int get completedLevelsCount => levels.where((l) => l.isCompleted).length;

  LearningCourse copyWith({
    String? id,
    String? subjectId,
    String? subjectName,
    String? title,
    String? subtitle,
    String? description,
    int? iconCodePoint,
    int? progressPercent,
    List<CourseLevel>? levels,
    String? cadenceInsight,
  }) {
    return LearningCourse(
      id: id ?? this.id,
      subjectId: subjectId ?? this.subjectId,
      subjectName: subjectName ?? this.subjectName,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      description: description ?? this.description,
      iconCodePoint: iconCodePoint ?? this.iconCodePoint,
      progressPercent: progressPercent ?? this.progressPercent,
      levels: levels ?? this.levels,
      cadenceInsight: cadenceInsight ?? this.cadenceInsight,
    );
  }
}

class CourseRepository {
  static List<LearningCourse> getCoursesForSubject(
    String subjectName, {
    String grade = 'Class 10',
    String subjectId = '',
  }) {
    final lower = subjectName.toLowerCase().trim();

    if (lower.contains('math')) {
      return _mathCourses;
    } else if (lower.contains('science')) {
      return _scienceCourses;
    } else if (lower.contains('english') || lower.contains('lit')) {
      return _englishCourses;
    } else if (lower.contains('social') || lower.contains('history') || lower.contains('geo')) {
      return _socialStudiesCourses;
    }

    // Dynamic fallback for any user-added custom subjects
    return _generateCustomCourses(subjectName, subjectId);
  }

  static List<LearningCourse> getAllCourses() {
    return [
      ..._mathCourses,
      ..._scienceCourses,
      ..._englishCourses,
      ..._socialStudiesCourses,
    ];
  }

  static LearningCourse? getCourseById(String id, {String grade = 'Class 10'}) {
    final all = getAllCourses();
    for (final c in all) {
      if (c.id == id) return c;
    }
    return null;
  }

  // === MATHEMATICS COURSES ===
  static final List<LearningCourse> _mathCourses = [
    LearningCourse(
      id: 'math_algebra',
      subjectId: 'math',
      subjectName: 'Mathematics',
      title: 'Algebra & Functions',
      subtitle: 'Equations, Graphs & Polynomials',
      description: 'Master foundational algebraic manipulations, linear systems, quadratic functions, and graphical representations.',
      iconCodePoint: Icons.calculate_outlined.codePoint,
      progressPercent: 74,
      cadenceInsight: 'You consistently perform best when reviewing algebraic graphs in 15-minute bursts. Keep the steady momentum!',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Variables & Algebraic Expressions',
          description: 'Introduction to symbols, combining like terms, and evaluating single-variable expressions.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Algebraic Expressions & Like Terms',
          keyConcepts: ['Variables as placeholders', 'Evaluating expressions', 'Distributive property'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'One-Step & Two-Step Equations',
          description: 'Balancing equations using inverse operations and isolating unknown variables.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '8 min',
          quizTopic: 'Linear Equations in One Variable',
          keyConcepts: ['Additive and multiplicative inverses', 'Isolating the variable', 'Checking solutions'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • LINEAR SYSTEMS',
          title: 'Solving Linear Equations',
          description: 'Solving multi-step equations with variables on both sides, parentheses, and fractional coefficients.',
          status: LevelStatus.active,
          stepProgress: 'Step 3 of 5',
          duration: '8 min',
          quizTopic: 'Multi-step Linear Equations',
          keyConcepts: ['Clearing denominators', 'Combining like terms', 'Infinite vs no solution'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • COORDINATE MAPS',
          title: 'Slope-Intercept & Graphing',
          description: 'Graphing linear relations on Cartesian planes, interpreting slope (m) and y-intercept (b).',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Slope and Graphing Lines',
          keyConcepts: ['Rise over run', 'y = mx + b', 'Parallel and perpendicular lines'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • QUADRATICS',
          title: 'Quadratic Functions & Factoring',
          description: 'Factoring trinomials, the quadratic formula, and parabolic vertex transformations.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Quadratic Equations & Parabolas',
          keyConcepts: ['Zero product property', 'x = (-b ± √(b² - 4ac)) / 2a', 'Vertex form'],
        ),
      ],
    ),
    LearningCourse(
      id: 'math_geometry',
      subjectId: 'math',
      subjectName: 'Mathematics',
      title: 'Coordinate Geometry',
      subtitle: 'Shapes, Proofs & Coordinate Planes',
      description: 'Explore geometric proofs, angles, Pythagorean theorem, coordinate distances, and circular geometry.',
      iconCodePoint: Icons.square_foot_outlined.codePoint,
      progressPercent: 40,
      cadenceInsight: 'Visualizing geometric diagrams before solving increases proof accuracy by 35%.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Points, Lines & Angles',
          description: 'Complementary, supplementary, and vertically opposite angle relationships.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Angles & Parallel Lines',
          keyConcepts: ['Transversals', 'Alternate interior angles', 'Angle sum property'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Triangles & Congruence',
          description: 'Congruence criteria (SSS, SAS, ASA, RHS) and triangle inequalities.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '8 min',
          quizTopic: 'Triangle Congruence Proofs',
          keyConcepts: ['CPCTC', 'Isosceles triangle theorem', 'Hypotenuse-leg theorem'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • PYTHAGORAS',
          title: 'Distance & Pythagorean Theorem',
          description: 'Distance formula in 2D coordinates and right-triangle trigonometry.',
          status: LevelStatus.active,
          stepProgress: 'Step 2 of 5',
          duration: '9 min',
          quizTopic: 'Distance Formula & Pythagorean Theorem',
          keyConcepts: ['d = √((x₂-x₁)² + (y₂-y₁)²)'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • CIRCLES',
          title: 'Circle Theorems & Chords',
          description: 'Inscribed angles, tangents, radii, and arc length formulas.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Circle Theorems & Tangents',
          keyConcepts: ['Radius-tangent perpendicularity', 'Inscribed angle theorem'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • 3D SOLIDS',
          title: 'Surface Area & Volume',
          description: 'Prisms, cylinders, cones, and spheres cross-sections and packing problems.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: '3D Geometry & Solid Volumes',
          keyConcepts: ['Cavalieri’s principle', 'Surface integrals in solid geometry'],
        ),
      ],
    ),
    LearningCourse(
      id: 'math_trig',
      subjectId: 'math',
      subjectName: 'Mathematics',
      title: 'Trigonometry & Vectors',
      subtitle: 'Sine, Cosine, Angles & Navigation',
      description: 'From right-triangle ratios to the unit circle, wave graphing, and 2D vector applications.',
      iconCodePoint: Icons.show_chart_rounded.codePoint,
      progressPercent: 20,
      cadenceInsight: 'Reviewing the unit circle reference angles daily solidifies exact values without calculator reliance.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'SOH CAH TOA Ratios',
          description: 'Definitions of sin, cos, and tan in right-angled triangles.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Right Triangle Trigonometric Ratios',
          keyConcepts: ['Opposite over hypotenuse', 'Adjacent over hypotenuse', 'Angles of elevation'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'The Unit Circle & Radian Measure',
          description: 'Converting degrees to radians and tracking coordinates on the unit circle.',
          status: LevelStatus.active,
          stepProgress: 'Step 1 of 5',
          duration: '8 min',
          quizTopic: 'Unit Circle & Radians',
          keyConcepts: ['π radians = 180°', '(cos θ, sin θ) on unit circle'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • IDENTITIES',
          title: 'Pythagorean Trigonometric Identities',
          description: 'Proving sin²θ + cos²θ = 1 and reciprocal relations.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '9 min',
          quizTopic: 'Trig Identities & Proofs',
          keyConcepts: ['sin²θ + cos²θ = 1', 'tan²θ + 1 = sec²θ'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • SINE & COSINE LAWS',
          title: 'Non-Right Triangles & Vectors',
          description: 'Solving oblique triangles and resolving vector magnitude and direction.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Law of Sines & Cosines',
          keyConcepts: ['a / sin A = b / sin B', 'c² = a² + b² - 2ab cos C'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • HARMONIC WAVES',
          title: 'Trigonometric Graphs & Periodicity',
          description: 'Amplitude, period, phase shifts, and modeling periodic phenomena.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Trig Graphs & Harmonic Motion',
          keyConcepts: ['y = A sin(Bx - C) + D', 'Frequency and wavelength'],
        ),
      ],
    ),
    LearningCourse(
      id: 'math_calculus',
      subjectId: 'math',
      subjectName: 'Mathematics',
      title: 'Calculus Foundations',
      subtitle: 'Limits, Rates of Change & Integrals',
      description: 'The mathematics of motion, tangent gradients, instantaneous velocities, and area accumulation.',
      iconCodePoint: Icons.trending_up_rounded.codePoint,
      progressPercent: 10,
      cadenceInsight: 'Connecting physical velocity to mathematical derivative graphs builds lasting conceptual intuition.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Limits & Continuity',
          description: 'Evaluating limits analytically and recognizing jump or removable discontinuities.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '7 min',
          quizTopic: 'Limits & Continuity',
          keyConcepts: ['Left- and right-hand limits', 'Squeeze theorem', 'Continuity criteria'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • DERIVATIVES',
          title: 'Definition of Derivative & Power Rule',
          description: 'Finding instantaneous slope with limits of difference quotients and power rule shortcut.',
          status: LevelStatus.active,
          stepProgress: 'Step 2 of 5',
          duration: '9 min',
          quizTopic: 'Power Rule & First Derivatives',
          keyConcepts: ['d/dx [x^n] = n x^(n-1)', 'Tangent line equations'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • RULES & EXTENSIONS',
          title: 'Product, Quotient & Chain Rules',
          description: 'Differentiating composite, multiplicative, and rational functions.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          quizTopic: 'Product, Quotient & Chain Rules',
          keyConcepts: ['Chain rule: f’(g(x)) · g’(x)', 'Implicit differentiation'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • OPTIMIZATION',
          title: 'Extrema & Curve Sketching',
          description: 'First and second derivative tests, concavity, inflection points, and real-world optimization.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '11 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Critical Points & Optimization',
          keyConcepts: ['f’(x) = 0 critical values', 'Second derivative concavity test'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • INTEGRATION',
          title: 'Antiderivatives & Fundamental Theorem',
          description: 'Riemann sums, definite integrals, and area bounded beneath curves.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Definite Integrals & Fundamental Theorem',
          keyConcepts: ['∫ f(x) dx = F(b) - F(a)', 'Substitution method'],
        ),
      ],
    ),
  ];

  // === SCIENCE COURSES ===
  static final List<LearningCourse> _scienceCourses = [
    LearningCourse(
      id: 'sci_physics',
      subjectId: 'science',
      subjectName: 'Science',
      title: 'Physics',
      subtitle: 'Mechanics, Optics & Thermodynamics',
      description: 'Newtonian mechanics, energy conservation, wave optics, electricity, and modern quantum insights.',
      iconCodePoint: Icons.bolt_rounded.codePoint,
      progressPercent: 62,
      cadenceInsight: 'Drawing free-body force diagrams first resolves 85% of mechanics exam mistakes.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Kinematics & Motion',
          description: 'Displacement, velocity, uniform acceleration, and equations of motion.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Motion & Kinematics Equations',
          keyConcepts: ['v = u + at', 's = ut + ½at²', 'v² = u² + 2as'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Newton’s Laws & Forces',
          description: 'Inertia, F = ma, action-reaction pairs, and friction analysis.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '8 min',
          quizTopic: 'Newton’s Laws of Motion',
          keyConcepts: ['Net force', 'Inertial frames', 'Terminal velocity'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • ENERGY & WORK',
          title: 'Work, Energy & Momentum',
          description: 'Kinetic energy, gravitational potential energy, power, and elastic collisions.',
          status: LevelStatus.active,
          stepProgress: 'Step 3 of 5',
          duration: '8 min',
          quizTopic: 'Conservation of Energy & Momentum',
          keyConcepts: ['Work W = F · d · cos θ', 'KE = ½mv²', 'Conservation of momentum'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • ELECTRICITY',
          title: 'Current & Electric Circuits',
          description: 'Ohm’s law, series vs parallel resistors, Kirchhoff’s laws, and electrical power.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Electric Circuits & Ohm’s Law',
          keyConcepts: ['V = I · R', 'Equivalent resistance', 'P = V · I = I² · R'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • LIGHT & OPTICS',
          title: 'Refraction & Wave Optics',
          description: 'Snell’s law, lenses, mirrors, total internal reflection, and optical instruments.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Optics & Wave Refraction',
          keyConcepts: ['n₁ sin θ₁ = n₂ sin θ₂', 'Lens maker’s formula'],
        ),
      ],
    ),
    LearningCourse(
      id: 'sci_chemistry',
      subjectId: 'science',
      subjectName: 'Science',
      title: 'Chemistry',
      subtitle: 'Atoms, Reactions & Organic Compounds',
      description: 'Subatomic structures, periodic trends, chemical bonding, stoichiometry, and carbon chemistry.',
      iconCodePoint: Icons.science_outlined.codePoint,
      progressPercent: 48,
      cadenceInsight: 'Mastering electron shell diagrams makes chemical valence and bond types intuitive.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Atomic Structure & Periodic Trends',
          description: 'Protons, neutrons, electrons, electron configuration, and electronegativity trends.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Atomic Structure & Periodic Table',
          keyConcepts: ['Atomic number vs mass', 'Valence electrons', 'Ionization energy'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Chemical Bonding & Molecules',
          description: 'Ionic lattice vs covalent sharing, polar molecules, and metallic bonds.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '8 min',
          quizTopic: 'Chemical Bonding: Ionic & Covalent',
          keyConcepts: ['Octet rule', 'Electronegativity difference', 'Lewis dot structures'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • STOICHIOMETRY',
          title: 'Balancing Equations & Mole Concept',
          description: 'Mole calculations, Avogadro’s constant, molar mass, and limiting reactants.',
          status: LevelStatus.active,
          stepProgress: 'Step 2 of 5',
          duration: '8 min',
          quizTopic: 'Stoichiometry & Mole Calculations',
          keyConcepts: ['Avogadro’s number (6.022 × 10²³)', 'Molar ratios', 'Conservation of mass'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • ACIDS & BASES',
          title: 'Acids, Bases & Neutralization',
          description: 'pH scale, Arrhenius and Bronsted-Lowry theories, indicators, and salt preparation.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Acids, Bases & pH Calculations',
          keyConcepts: ['pH = -log[H⁺]', 'Neutralization reactions', 'Buffer solutions'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • CARBON CHEMISTRY',
          title: 'Carbon & Organic Compounds',
          description: 'Hydrocarbons (alkanes, alkenes, alkynes), functional groups, and isomerism.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Carbon & Its Compounds',
          keyConcepts: ['Tetravalency & catenation', 'Functional groups', 'Saponification & micelles'],
        ),
      ],
    ),
    LearningCourse(
      id: 'sci_biology',
      subjectId: 'science',
      subjectName: 'Science',
      title: 'Biology',
      subtitle: 'Cells, Human Physiology & Genetics',
      description: 'Cell organelles, bioenergetics, circulatory & nervous systems, DNA replication, and evolutionary genetics.',
      iconCodePoint: Icons.biotech_rounded.codePoint,
      progressPercent: 35,
      cadenceInsight: 'Tracing bio pathways sequentially (DNA ⟶ RNA ⟶ Protein) makes molecular biology stick.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Cell Organelles & Transport',
          description: 'Structure of prokaryotic vs eukaryotic cells, osmosis, and active transport.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Cell Structures & Organelles',
          keyConcepts: ['Mitochondria ATP', 'Ribosomes', 'Semi-permeable cell membrane'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Photosynthesis & Respiration',
          description: 'Chloroplast light reactions, Calvin cycle, glycolysis, and aerobic Krebs cycle.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '8 min',
          quizTopic: 'Cellular Respiration & Photosynthesis',
          keyConcepts: ['Photosynthesis equation', 'Aerobic vs anaerobic respiration'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • PHYSIOLOGY',
          title: 'Circulation & Nervous Coordination',
          description: 'Human four-chambered heart, double circulation, neuron action potentials, and reflex arcs.',
          status: LevelStatus.active,
          stepProgress: 'Step 4 of 5',
          duration: '9 min',
          quizTopic: 'Human Circulatory & Nervous Systems',
          keyConcepts: ['Systemic vs pulmonary circulation', 'Neuron synapses', 'Reflex arc pathway'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • GENETICS',
          title: 'Mendelian Genetics & DNA',
          description: 'Monohybrid and dihybrid crosses, Punnett squares, DNA double helix, and mutations.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Genetics & Mendelian Inheritance',
          keyConcepts: ['Dominant vs recessive alleles', '3:1 phenotypic ratio', 'Base-pairing rules'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • ECOLOGY',
          title: 'Ecosystems & Biodiversity',
          description: 'Trophic levels, energy pyramid 10% rule, nitrogen cycle, and conservation biology.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Ecosystems & Food Webs',
          keyConcepts: ['10% energy transfer rule', 'Bioaccumulation', 'Biogeochemical cycles'],
        ),
      ],
    ),
  ];

  // === ENGLISH COURSES ===
  static final List<LearningCourse> _englishCourses = [
    LearningCourse(
      id: 'eng_grammar',
      subjectId: 'english',
      subjectName: 'English',
      title: 'Grammar & Mechanics',
      subtitle: 'Syntax, Tenses & Clause Analysis',
      description: 'Master sentence structure, active vs passive voice, subject-verb agreement, and flawless punctuation.',
      iconCodePoint: Icons.spellcheck_rounded.codePoint,
      progressPercent: 55,
      cadenceInsight: 'Writing your own sample sentences after learning each grammar rule accelerates retention.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Parts of Speech & Sentence Core',
          description: 'Identifying nouns, pronouns, verbs, adjectives, adverbs, prepositions, and conjunctions.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Parts of Speech & Syntax',
          keyConcepts: ['Subject and predicate', 'Direct and indirect objects'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Verb Tenses & Consistency',
          description: 'Simple, continuous, perfect, and perfect continuous tenses across past, present, and future.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '8 min',
          quizTopic: 'Verb Tenses & Agreement',
          keyConcepts: ['Past perfect vs simple past', 'Subject-verb agreement rules'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • CLAUSES',
          title: 'Active Voice & Complex Clauses',
          description: 'Transforming active to passive voice, dependent relative clauses, and subjunctive mood.',
          status: LevelStatus.active,
          stepProgress: 'Step 3 of 5',
          duration: '8 min',
          quizTopic: 'Active and Passive Voice',
          keyConcepts: ['Object becomes subject', 'Agent preposition by', 'Relative pronouns'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • PUNCTUATION',
          title: 'Semicolons, Colons & Modifiers',
          description: 'Eliminating run-on sentences, dangling participles, and mastering advanced punctuation.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '9 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Advanced Punctuation & Modifiers',
          keyConcepts: ['Semicolon linking independent clauses', 'Avoiding misplaced modifiers'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • RHETORIC',
          title: 'Rhetorical Devices & Style',
          description: 'Parallelism, chiasmus, antithesis, and elevated sentence cadence.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '11 min',
          quizTopic: 'Rhetorical Devices & Style',
          keyConcepts: ['Parallel grammatical structures', 'Tone and diction control'],
        ),
      ],
    ),
    LearningCourse(
      id: 'eng_reading',
      subjectId: 'english',
      subjectName: 'English',
      title: 'Reading Comprehension',
      subtitle: 'Inference, Themes & Critical Analysis',
      description: 'Deconstruct complex non-fiction and literary passages, identify author tone, and draw textual evidence.',
      iconCodePoint: Icons.auto_stories_rounded.codePoint,
      progressPercent: 30,
      cadenceInsight: 'Annotating the main idea of each paragraph before answering comprehension questions saves exam time.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Main Ideas & Supporting Details',
          description: 'Differentiating central thesis from supporting illustrations in expository texts.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Main Idea & Paragraph Topic',
          keyConcepts: ['Topic sentences', 'Distinguishing fact from opinion'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Inference & Context Clues',
          description: 'Reading between the lines and decoding unfamiliar academic vocabulary from surrounding text.',
          status: LevelStatus.active,
          stepProgress: 'Step 2 of 5',
          duration: '8 min',
          quizTopic: 'Inference & Vocabulary in Context',
          keyConcepts: ['Textual evidence justification', 'Tone and mood cues'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • ARGUMENTATION',
          title: 'Author’s Purpose & Bias',
          description: 'Evaluating claims, identifying logical fallacies, and analyzing counterarguments.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '9 min',
          quizTopic: 'Author’s Purpose & Rhetorical Appeal',
          keyConcepts: ['Ethos, pathos, logos', 'Ad hominem and straw man fallacies'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • LITERATURE',
          title: 'Symbolism & Poetic Devices',
          description: 'Metaphor, allegory, irony, personification, and meter in classical poetry.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Literary Devices & Figurative Language',
          keyConcepts: ['Dramatic vs situational irony', 'Extended metaphor'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • CRITICAL SYNTHESIS',
          title: 'Paired Passage Synthesis',
          description: 'Comparing conflicting perspectives across two historical or argumentative texts.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Comparative Reading & Textual Synthesis',
          keyConcepts: ['Synthesizing opposing viewpoints', 'Nuanced comparative analysis'],
        ),
      ],
    ),
  ];

  // === SOCIAL STUDIES COURSES ===
  static final List<LearningCourse> _socialStudiesCourses = [
    LearningCourse(
      id: 'soc_history',
      subjectId: 'social',
      subjectName: 'Social Studies',
      title: 'World & National History',
      subtitle: 'Civilizations, Revolutions & Modernity',
      description: 'Explore the rise of ancient civilizations, colonial impacts, industrialization, and global struggles.',
      iconCodePoint: Icons.history_edu_rounded.codePoint,
      progressPercent: 50,
      cadenceInsight: 'Studying history as cause-and-effect narratives rather than isolated dates creates vivid memory anchors.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Ancient River Civilizations',
          description: 'Mesopotamia, Indus Valley, Nile, and early agricultural settlements.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Ancient Civilizations & Urban Centers',
          keyConcepts: ['Urban planning & trade routes', 'Cuneiform & early codices'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'The Age of Enlightenment',
          description: 'Scientific revolution, social contract theory, and ideas leading to democratic governance.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '8 min',
          quizTopic: 'Enlightenment & Political Philosophy',
          keyConcepts: ['Locke, Montesquieu, Rousseau', 'Separation of powers'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • REVOLUTIONS',
          title: 'Industrial & Democratic Revolutions',
          description: 'Steam power, urbanization, labor movements, and the French & American revolutions.',
          status: LevelStatus.active,
          stepProgress: 'Step 3 of 5',
          duration: '9 min',
          quizTopic: 'The Industrial Revolution & Global Change',
          keyConcepts: ['Factory systems and urbanization', 'Declaration of Rights'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • WORLD WARS',
          title: 'World Conflicts & The UN',
          description: 'Alliances of WWI & WWII, the Holocaust, atomic weapons, and the League of Nations & UN creation.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'World Wars & Global Geopolitics',
          keyConcepts: ['Treaty of Versailles', 'United Nations Charter'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • MODERN ERA',
          title: 'Decolonization & Globalization',
          description: 'Anti-colonial movements, independence in Asia & Africa, the Cold War, and digital globalization.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Decolonization & Modern World',
          keyConcepts: ['Non-Aligned Movement', 'Global economic interdependence'],
        ),
      ],
    ),
    LearningCourse(
      id: 'soc_geography',
      subjectId: 'social',
      subjectName: 'Social Studies',
      title: 'Physical & Human Geography',
      subtitle: 'Landforms, Climate, Maps & Resources',
      description: 'Plate tectonics, weather patterns, population demographics, cartography, and sustainable resource use.',
      iconCodePoint: Icons.public_rounded.codePoint,
      progressPercent: 32,
      cadenceInsight: 'Correlating climate zones with global air pressure belts clarifies worldwide rainfall distribution.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'Earth’s Structure & Plate Tectonics',
          description: 'Crust, mantle, core, continental drift, and earthquake fault lines.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Plate Tectonics & Earth Layers',
          keyConcepts: ['Convergent vs divergent boundaries', 'Ring of Fire'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Atmosphere & Global Climate',
          description: 'Atmospheric layers, Coriolis effect, monsoons, and tropical cyclogenesis.',
          status: LevelStatus.active,
          stepProgress: 'Step 2 of 5',
          duration: '8 min',
          quizTopic: 'Atmospheric Pressure & Monsoons',
          keyConcepts: ['Troposphere to exosphere', 'High and low pressure systems'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • HYDROLOGY',
          title: 'River Systems & Coastal Landforms',
          description: 'Drainage basins, erosion, oxbow lakes, deltas, and oceanic currents.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '9 min',
          quizTopic: 'Hydrology & Landform Formation',
          keyConcepts: ['Upper vs lower course erosion', 'Thermohaline circulation'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • HUMAN SETTLEMENTS',
          title: 'Demographics & Urban Planning',
          description: 'Population density, demographic transition model, and rural-to-urban migration.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Population Demographics & Migration',
          keyConcepts: ['Age-sex pyramids', 'Push and pull migration factors'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • SUSTAINABILITY',
          title: 'Resource Management & Climate Action',
          description: 'Renewable vs non-renewable resources, carbon footprints, and sustainable development goals.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Natural Resources & Conservation',
          keyConcepts: ['Sustainable development goals', 'Renewable energy transitions'],
        ),
      ],
    ),
    LearningCourse(
      id: 'soc_civics',
      subjectId: 'social',
      subjectName: 'Social Studies',
      title: 'Civics & Governance',
      subtitle: 'Constitutions, Rights & Democracy',
      description: 'Democratic institutions, fundamental human rights, judiciary balance, and citizen engagement.',
      iconCodePoint: Icons.account_balance_rounded.codePoint,
      progressPercent: 25,
      cadenceInsight: 'Mapping checks-and-balances between branches of government clarifies constitutional democracy.',
      levels: const [
        CourseLevel(
          levelNumber: 1,
          code: '01 • FOUNDATIONS',
          title: 'What is Democracy?',
          description: 'Direct vs representative democracy, rule of law, and universal adult franchise.',
          status: LevelStatus.completed,
          stepProgress: 'Step 5 of 5',
          duration: '6 min',
          quizTopic: 'Principles of Democracy & Governance',
          keyConcepts: ['Free and fair elections', 'Majority rule with minority rights'],
        ),
        CourseLevel(
          levelNumber: 2,
          code: '02 • BASICS',
          title: 'Constitutional Architecture',
          description: 'The preamble, fundamental rights, directive principles, and amendment procedures.',
          status: LevelStatus.active,
          stepProgress: 'Step 2 of 5',
          duration: '8 min',
          quizTopic: 'Constitutional Rights & Duties',
          keyConcepts: ['Preamble core values', 'Writ jurisdiction'],
        ),
        CourseLevel(
          levelNumber: 3,
          code: '03 • THREE BRANCHES',
          title: 'Legislature, Executive & Judiciary',
          description: 'Passing bills, cabinet responsibility, judicial review, and checks and balances.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '9 min',
          quizTopic: 'The Three Branches of Government',
          keyConcepts: ['Bicameral legislature', 'Independent judiciary'],
        ),
        CourseLevel(
          levelNumber: 4,
          code: '04 • LOCAL GOVERNANCE',
          title: 'Federalism & Decentralization',
          description: 'National vs state powers, local councils (Panchayats/Municipalities), and civic participation.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '10 min',
          hasBonus: true,
          bonusTitle: 'DAILY SPEED RUN',
          quizTopic: 'Federalism & Local Government',
          keyConcepts: ['Union, State, and Concurrent lists', 'Grassroots democracy'],
        ),
        CourseLevel(
          levelNumber: 5,
          code: '05 • GLOBAL RIGHTS',
          title: 'Human Rights & International Law',
          description: 'Universal Declaration of Human Rights, international courts, and global humanitarian law.',
          status: LevelStatus.locked,
          stepProgress: 'Step 0 of 5',
          duration: '12 min',
          quizTopic: 'Universal Human Rights & Law',
          keyConcepts: ['Geneva conventions', 'International Court of Justice'],
        ),
      ],
    ),
  ];

  // Dynamic generator for user-added subjects
  static List<LearningCourse> _generateCustomCourses(String name, String id) {
    return [
      LearningCourse(
        id: '${id.isEmpty ? 'custom' : id}_core',
        subjectId: id,
        subjectName: name,
        title: '$name Essentials',
        subtitle: 'Core Principles & Key Concepts',
        description: 'Comprehensive guided progression covering essential fundamentals and practical problem-solving in $name.',
        iconCodePoint: Icons.school_rounded.codePoint,
        progressPercent: 50,
        cadenceInsight: 'Consistent review of core principles in $name yields maximum retention and test confidence.',
        levels: [
          CourseLevel(
            levelNumber: 1,
            code: '01 • FOUNDATIONS',
            title: 'Core Terminology & Basics',
            description: 'Primary vocabulary, foundational premises, and historical context of $name.',
            status: LevelStatus.completed,
            stepProgress: 'Step 5 of 5',
            duration: '6 min',
            quizTopic: '$name Fundamentals',
            keyConcepts: ['Key definitions', 'Foundational frameworks'],
          ),
          CourseLevel(
            levelNumber: 2,
            code: '02 • BASICS',
            title: 'Essential Methods & Frameworks',
            description: 'Core procedural steps, standard formulas, and analytical techniques.',
            status: LevelStatus.completed,
            stepProgress: 'Step 5 of 5',
            duration: '8 min',
            quizTopic: '$name Core Techniques',
            keyConcepts: ['Standard methodologies', 'Systematic problem solving'],
          ),
          CourseLevel(
            levelNumber: 3,
            code: '03 • APPLIED PRACTICE',
            title: 'Applied Problem Solving',
            description: 'Hands-on practice tackling intermediate analytical challenges.',
            status: LevelStatus.active,
            stepProgress: 'Step 3 of 5',
            duration: '8 min',
            quizTopic: '$name Applied Exercises',
            keyConcepts: ['Real-world modeling', 'Error mitigation'],
          ),
          CourseLevel(
            levelNumber: 4,
            code: '04 • ADVANCED DRILLS',
            title: 'Advanced Synthesis & Insights',
            description: 'Integrating multiple concepts to solve multi-part scenario problems.',
            status: LevelStatus.locked,
            stepProgress: 'Step 0 of 5',
            duration: '10 min',
            hasBonus: true,
            bonusTitle: 'DAILY SPEED RUN',
            quizTopic: '$name Advanced Synthesis',
            keyConcepts: ['Complex case studies', 'Evaluation criteria'],
          ),
          CourseLevel(
            levelNumber: 5,
            code: '05 • MASTERY',
            title: 'Mastery Challenge & Capstone',
            description: 'Comprehensive final examination simulating real competitive assessment conditions.',
            status: LevelStatus.locked,
            stepProgress: 'Step 0 of 5',
            duration: '12 min',
            quizTopic: '$name Capstone Mastery',
            keyConcepts: ['Synthesis under timed constraints', 'Exhaustive verification'],
          ),
        ],
      ),
    ];
  }
}
